export const getCorrectMidiNoteEvents = () => {
	return [
		{
			note: 5,
			startBeat: 0,
			endBeat: 0.5,
			velocity: 0.9,
			correct: true,
			id: 1,
			selected: false,
		},
		{
			note: 0,
			startBeat: 0.5,
			endBeat: 1,
			velocity: 0.9,
			correct: true,
			id: 600,
			selected: false,
		},
		{
			note: 3,
			startBeat: 1,
			endBeat: 1.5,
			velocity: 0.9,
			correct: true,
			id: 229,
			selected: false,
		},
		{
			note: 5,
			startBeat: 1.5,
			endBeat: 1.625,
			velocity: 0.9,
			correct: true,
			id: 934,
			selected: false,
		},
		{
			note: 5,
			startBeat: 1.625,
			endBeat: 1.75,
			velocity: 0.9,
			correct: true,
			id: 936,
			selected: false,
		},
		{
			note: 5,
			startBeat: 1.75,
			endBeat: 1.875,
			velocity: 0.9,
			correct: true,
			id: 933,
			selected: false,
		},
		{
			note: 5,
			startBeat: 1.875,
			endBeat: 2,
			velocity: 0.9,
			correct: true,
			id: 925,
			selected: false,
		},
		{
			note: 1,
			startBeat: 2,
			endBeat: 2.5,
			velocity: 0.9,
			correct: true,
			id: 919,
			selected: false,
		},
		{
			note: 5,
			startBeat: 3,
			endBeat: 3.25,
			velocity: 0.9,
			correct: true,
			id: 938,
			selected: false,
		},
		{
			note: 5,
			startBeat: 3.25,
			endBeat: 3.5,
			velocity: 0.9,
			correct: true,
			id: 940,
			selected: false,
		},
		{
			note: 2,
			startBeat: 3.5,
			endBeat: 4,
			velocity: 0.9,
			correct: true,
			id: 393,
			selected: false,
		},
		{
			note: 2,
			startBeat: 4.5,
			endBeat: 5,
			velocity: 0.9,
			correct: true,
			id: 387,
			selected: false,
		},
		{
			note: 5,
			startBeat: 5,
			endBeat: 5.5,
			velocity: 0.9,
			correct: true,
			id: 65,
			selected: false,
		},
		{
			note: 5,
			startBeat: 5.5,
			endBeat: 6,
			velocity: 0.9,
			correct: true,
			id: 68,
			selected: false,
		},
		{
			note: 1,
			startBeat: 6,
			endBeat: 6.5,
			velocity: 0.9,
			correct: true,
			id: 450,
			selected: false,
		},
		{
			note: 4,
			startBeat: 6.5,
			endBeat: 7,
			velocity: 0.9,
			correct: true,
			id: 185,
			selected: false,
		},
		{
			note: 4,
			startBeat: 7,
			endBeat: 7.5,
			velocity: 0.9,
			correct: true,
			id: 182,
			selected: false,
		},
		{
			note: 4,
			startBeat: 7.5,
			endBeat: 8,
			velocity: 0.9,
			correct: true,
			id: 179,
			selected: false,
		},
		{
			note: 5,
			startBeat: 8,
			endBeat: 8.5,
			velocity: 0.9,
			correct: true,
			id: 83,
			selected: false,
		},
		{
			note: 3,
			startBeat: 9,
			endBeat: 9.5,
			velocity: 0.9,
			correct: true,
			id: 277,
			selected: false,
		},
		{
			note: 0,
			startBeat: 9.5,
			endBeat: 10,
			velocity: 0.9,
			correct: true,
			id: 546,
			selected: false,
		},
		{
			note: 1,
			startBeat: 10,
			endBeat: 10.5,
			velocity: 0.9,
			correct: true,
			id: 918,
			selected: false,
		},
		{
			note: 5,
			startBeat: 11,
			endBeat: 11.25,
			velocity: 0.9,
			correct: true,
			id: 942,
			selected: false,
		},
		{
			note: 5,
			startBeat: 11.25,
			endBeat: 11.5,
			velocity: 0.9,
			correct: true,
			id: 944,
			selected: false,
		},
		{
			note: 2,
			startBeat: 11.5,
			endBeat: 12,
			velocity: 0.9,
			correct: true,
			id: 345,
			selected: false,
		},
		{
			note: 2,
			startBeat: 12.5,
			endBeat: 13,
			velocity: 0.9,
			correct: true,
			id: 339,
			selected: false,
		},
		{
			note: 5,
			startBeat: 13,
			endBeat: 13.5,
			velocity: 0.9,
			correct: true,
			id: 113,
			selected: false,
		},
		{
			note: 5,
			startBeat: 13.5,
			endBeat: 14,
			velocity: 0.9,
			correct: true,
			id: 116,
			selected: false,
		},
		{
			note: 1,
			startBeat: 14,
			endBeat: 14.5,
			velocity: 0.9,
			correct: true,
			id: 498,
			selected: false,
		},
		{
			note: 5,
			startBeat: 14.5,
			endBeat: 15,
			velocity: 0.9,
			correct: true,
			id: 122,
			selected: false,
		},
		{
			note: 4,
			startBeat: 15,
			endBeat: 15.5,
			velocity: 0.9,
			correct: true,
			id: 134,
			selected: false,
		},
		{
			note: 5,
			startBeat: 15.5,
			endBeat: 16,
			velocity: 0.9,
			correct: true,
			id: 127,
			selected: false,
		},
	];
};

export const getCorrectData = () => {
	return [
		[
			{
				note: 0,
				startBeat: 9.5,
				endBeat: 10,
				velocity: 0.9,
				correct: true,
				id: 546,
				selected: false,
			},
			{
				note: 0,
				startBeat: 0.5,
				endBeat: 1,
				velocity: 0.9,
				correct: true,
				id: 600,
				selected: false,
			},
		],
		[
			{
				note: 1,
				startBeat: 6,
				endBeat: 6.5,
				velocity: 0.9,
				correct: true,
				id: 450,
				selected: false,
			},
			{
				note: 1,
				startBeat: 14,
				endBeat: 14.5,
				velocity: 0.9,
				correct: true,
				id: 498,
				selected: false,
			},
			{
				note: 1,
				startBeat: 10,
				endBeat: 10.5,
				velocity: 0.9,
				correct: true,
				id: 918,
				selected: false,
			},
			{
				note: 1,
				startBeat: 2,
				endBeat: 2.5,
				velocity: 0.9,
				correct: true,
				id: 919,
				selected: false,
			},
		],
		[
			{
				note: 2,
				startBeat: 12.5,
				endBeat: 13,
				velocity: 0.9,
				correct: true,
				id: 339,
				selected: false,
			},
			{
				note: 2,
				startBeat: 11.5,
				endBeat: 12,
				velocity: 0.9,
				correct: true,
				id: 345,
				selected: false,
			},
			{
				note: 2,
				startBeat: 4.5,
				endBeat: 5,
				velocity: 0.9,
				correct: true,
				id: 387,
				selected: false,
			},
			{
				note: 2,
				startBeat: 3.5,
				endBeat: 4,
				velocity: 0.9,
				correct: true,
				id: 393,
				selected: false,
			},
		],
		[
			{
				note: 3,
				startBeat: 1,
				endBeat: 1.5,
				velocity: 0.9,
				correct: true,
				id: 229,
				selected: false,
			},
			{
				note: 3,
				startBeat: 9,
				endBeat: 9.5,
				velocity: 0.9,
				correct: true,
				id: 277,
				selected: false,
			},
		],
		[
			{
				note: 4,
				startBeat: 15,
				endBeat: 15.5,
				velocity: 0.9,
				correct: true,
				id: 134,
				selected: false,
			},
			{
				note: 4,
				startBeat: 7.5,
				endBeat: 8,
				velocity: 0.9,
				correct: true,
				id: 179,
				selected: false,
			},
			{
				note: 4,
				startBeat: 7,
				endBeat: 7.5,
				velocity: 0.9,
				correct: true,
				id: 182,
				selected: false,
			},
			{
				note: 4,
				startBeat: 6.5,
				endBeat: 7,
				velocity: 0.9,
				correct: true,
				id: 185,
				selected: false,
			},
		],
		[
			{
				note: 5,
				startBeat: 0,
				endBeat: 0.5,
				velocity: 0.9,
				correct: true,
				id: 1,
				selected: false,
			},
			{
				note: 5,
				startBeat: 5,
				endBeat: 5.5,
				velocity: 0.9,
				correct: true,
				id: 65,
				selected: false,
			},
			{
				note: 5,
				startBeat: 5.5,
				endBeat: 6,
				velocity: 0.9,
				correct: true,
				id: 68,
				selected: false,
			},
			{
				note: 5,
				startBeat: 8,
				endBeat: 8.5,
				velocity: 0.9,
				correct: true,
				id: 83,
				selected: false,
			},
			{
				note: 5,
				startBeat: 13,
				endBeat: 13.5,
				velocity: 0.9,
				correct: true,
				id: 113,
				selected: false,
			},
			{
				note: 5,
				startBeat: 13.5,
				endBeat: 14,
				velocity: 0.9,
				correct: true,
				id: 116,
				selected: false,
			},
			{
				note: 5,
				startBeat: 14.5,
				endBeat: 15,
				velocity: 0.9,
				correct: true,
				id: 122,
				selected: false,
			},
			{
				note: 5,
				startBeat: 15.5,
				endBeat: 16,
				velocity: 0.9,
				correct: true,
				id: 127,
				selected: false,
			},
			{
				note: 5,
				startBeat: 1.875,
				endBeat: 2,
				velocity: 0.9,
				correct: true,
				id: 925,
				selected: false,
			},
			{
				note: 5,
				startBeat: 1.75,
				endBeat: 1.875,
				velocity: 0.9,
				correct: true,
				id: 933,
				selected: false,
			},
			{
				note: 5,
				startBeat: 1.5,
				endBeat: 1.625,
				velocity: 0.9,
				correct: true,
				id: 934,
				selected: false,
			},
			{
				note: 5,
				startBeat: 1.625,
				endBeat: 1.75,
				velocity: 0.9,
				correct: true,
				id: 936,
				selected: false,
			},
			{
				note: 5,
				startBeat: 3,
				endBeat: 3.25,
				velocity: 0.9,
				correct: true,
				id: 938,
				selected: false,
			},
			{
				note: 5,
				startBeat: 3.25,
				endBeat: 3.5,
				velocity: 0.9,
				correct: true,
				id: 940,
				selected: false,
			},
			{
				note: 5,
				startBeat: 11,
				endBeat: 11.25,
				velocity: 0.9,
				correct: true,
				id: 942,
				selected: false,
			},
			{
				note: 5,
				startBeat: 11.25,
				endBeat: 11.5,
				velocity: 0.9,
				correct: true,
				id: 944,
				selected: false,
			},
		],
	];
};
