export const getCorrectMidiNoteEvents = () => {
	return [
		{
			note: 0,
			startBeat: 0,
			endBeat: 0.5,
			velocity: 0.9,
			correct: true,
			id: 4,
			selected: false,
		},
		{
			note: 6,
			startBeat: 0,
			endBeat: 0.5,
			velocity: 0.9,
			correct: true,
			id: 23,
			selected: false,
		},
		{
			note: 1,
			startBeat: 0.5,
			endBeat: 1,
			velocity: 0.9,
			correct: true,
			id: 11,
			selected: false,
		},
		{
			note: 4,
			startBeat: 1,
			endBeat: 1.5,
			velocity: 0.9,
			correct: true,
			id: 24,
			selected: false,
		},
		{
			note: 6,
			startBeat: 1.5,
			endBeat: 1.625,
			velocity: 0.9,
			correct: true,
			id: 30,
			selected: false,
		},
		{
			note: 6,
			startBeat: 1.625,
			endBeat: 1.75,
			velocity: 0.9,
			correct: true,
			id: 33,
			selected: false,
		},
		{
			note: 6,
			startBeat: 1.75,
			endBeat: 1.875,
			velocity: 0.9,
			correct: true,
			id: 36,
			selected: false,
		},
		{
			note: 6,
			startBeat: 1.875,
			endBeat: 2,
			velocity: 0.9,
			correct: true,
			id: 38,
			selected: false,
		},
		{
			note: 2,
			startBeat: 2,
			endBeat: 2.5,
			velocity: 0.9,
			correct: true,
			id: 12,
			selected: false,
		},
		{
			note: 6,
			startBeat: 3,
			endBeat: 3.25,
			velocity: 0.9,
			correct: true,
			id: 41,
			selected: false,
		},
		{
			note: 6,
			startBeat: 3.25,
			endBeat: 3.5,
			velocity: 0.9,
			correct: true,
			id: 44,
			selected: false,
		},
		{
			note: 3,
			startBeat: 3.5,
			endBeat: 4,
			velocity: 0.9,
			correct: true,
			id: 13,
			selected: false,
		},
		{
			note: 3,
			startBeat: 4.5,
			endBeat: 5,
			velocity: 0.9,
			correct: true,
			id: 14,
			selected: false,
		},
		{
			note: 0,
			startBeat: 5,
			endBeat: 5.5,
			velocity: 0.9,
			correct: true,
			id: 5,
			selected: false,
		},
		{
			note: 6,
			startBeat: 5,
			endBeat: 5.25,
			velocity: 0.9,
			correct: true,
			id: 47,
			selected: false,
		},
		{
			note: 6,
			startBeat: 5.5,
			endBeat: 5.75,
			velocity: 0.9,
			correct: true,
			id: 48,
			selected: false,
		},
		{
			note: 2,
			startBeat: 6,
			endBeat: 6.5,
			velocity: 0.9,
			correct: true,
			id: 20,
			selected: true,
		},
		{
			note: 5,
			startBeat: 6.5,
			endBeat: 6.75,
			velocity: 0.9,
			correct: true,
			id: 51,
			selected: false,
		},
		{
			note: 5,
			startBeat: 7,
			endBeat: 7.25,
			velocity: 0.9,
			correct: true,
			id: 52,
			selected: false,
		},
		{
			note: 5,
			startBeat: 7.5,
			endBeat: 7.75,
			velocity: 0.9,
			correct: true,
			id: 53,
			selected: false,
		},
		{
			note: 0,
			startBeat: 8,
			endBeat: 8.5,
			velocity: 0.9,
			correct: true,
			id: 6,
			selected: false,
		},
		{
			note: 6,
			startBeat: 8,
			endBeat: 8.25,
			velocity: 0.9,
			correct: true,
			id: 54,
			selected: false,
		},
		{
			note: 4,
			startBeat: 9,
			endBeat: 9.25,
			velocity: 0.9,
			correct: true,
			id: 55,
			selected: false,
		},
		{
			note: 1,
			startBeat: 9.5,
			endBeat: 10,
			velocity: 0.9,
			correct: true,
			id: 56,
			selected: false,
		},
		{
			note: 2,
			startBeat: 10,
			endBeat: 10.5,
			velocity: 0.9,
			correct: true,
			id: 57,
			selected: false,
		},
		{
			note: 6,
			startBeat: 11,
			endBeat: 11.25,
			velocity: 0.9,
			correct: true,
			id: 60,
			selected: false,
		},
		{
			note: 6,
			startBeat: 11.25,
			endBeat: 11.5,
			velocity: 0.9,
			correct: true,
			id: 63,
			selected: false,
		},
		{
			note: 0,
			startBeat: 11.5,
			endBeat: 12,
			velocity: 0.9,
			correct: true,
			id: 8,
			selected: false,
		},
		{
			note: 3,
			startBeat: 11.5,
			endBeat: 11.75,
			velocity: 0.9,
			correct: true,
			id: 80,
			selected: false,
		},
		{
			note: 3,
			startBeat: 12.5,
			endBeat: 12.75,
			velocity: 0.9,
			correct: true,
			id: 79,
			selected: false,
		},
		{
			note: 0,
			startBeat: 13,
			endBeat: 13.5,
			velocity: 0.9,
			correct: true,
			id: 9,
			selected: false,
		},
		{
			note: 6,
			startBeat: 13,
			endBeat: 13.25,
			velocity: 0.9,
			correct: true,
			id: 67,
			selected: false,
		},
		{
			note: 6,
			startBeat: 13.5,
			endBeat: 13.75,
			velocity: 0.9,
			correct: true,
			id: 68,
			selected: false,
		},
		{
			note: 2,
			startBeat: 14,
			endBeat: 14.25,
			velocity: 0.9,
			correct: true,
			id: 78,
			selected: false,
		},
		{
			note: 0,
			startBeat: 14.5,
			endBeat: 15,
			velocity: 0.9,
			correct: true,
			id: 10,
			selected: false,
		},
		{
			note: 5,
			startBeat: 14.5,
			endBeat: 14.75,
			velocity: 0.9,
			correct: true,
			id: 83,
			selected: false,
		},
		{
			note: 6,
			startBeat: 15,
			endBeat: 15.25,
			velocity: 0.9,
			correct: true,
			id: 70,
			selected: false,
		},
		{
			note: 6,
			startBeat: 15.5,
			endBeat: 15.75,
			velocity: 0.9,
			correct: true,
			id: 81,
			selected: false,
		},
	];
};

export const getCorrectData = () => {
	return [
		[
			{
				note: 0,
				startBeat: 0,
				endBeat: 0.5,
				velocity: 0.9,
				correct: true,
				id: 4,
				selected: false,
			},
			{
				note: 0,
				startBeat: 5,
				endBeat: 5.5,
				velocity: 0.9,
				correct: true,
				id: 5,
				selected: false,
			},
			{
				note: 0,
				startBeat: 8,
				endBeat: 8.5,
				velocity: 0.9,
				correct: true,
				id: 6,
				selected: false,
			},
			{
				note: 0,
				startBeat: 11.5,
				endBeat: 12,
				velocity: 0.9,
				correct: true,
				id: 8,
				selected: false,
			},
			{
				note: 0,
				startBeat: 13,
				endBeat: 13.5,
				velocity: 0.9,
				correct: true,
				id: 9,
				selected: false,
			},
			{
				note: 0,
				startBeat: 14.5,
				endBeat: 15,
				velocity: 0.9,
				correct: true,
				id: 10,
				selected: false,
			},
		],
		[
			{
				note: 1,
				startBeat: 0.5,
				endBeat: 1,
				velocity: 0.9,
				correct: true,
				id: 11,
				selected: false,
			},
			{
				note: 1,
				startBeat: 9.5,
				endBeat: 10,
				velocity: 0.9,
				correct: true,
				id: 56,
				selected: false,
			},
		],
		[
			{
				note: 2,
				startBeat: 2,
				endBeat: 2.5,
				velocity: 0.9,
				correct: true,
				id: 12,
				selected: false,
			},
			{
				note: 2,
				startBeat: 6,
				endBeat: 6.5,
				velocity: 0.9,
				correct: true,
				id: 20,
				selected: true,
			},
			{
				note: 2,
				startBeat: 10,
				endBeat: 10.5,
				velocity: 0.9,
				correct: true,
				id: 57,
				selected: false,
			},
			{
				note: 2,
				startBeat: 14,
				endBeat: 14.25,
				velocity: 0.9,
				correct: true,
				id: 78,
				selected: false,
			},
		],
		[
			{
				note: 3,
				startBeat: 3.5,
				endBeat: 4,
				velocity: 0.9,
				correct: true,
				id: 13,
				selected: false,
			},
			{
				note: 3,
				startBeat: 4.5,
				endBeat: 5,
				velocity: 0.9,
				correct: true,
				id: 14,
				selected: false,
			},
			{
				note: 3,
				startBeat: 12.5,
				endBeat: 12.75,
				velocity: 0.9,
				correct: true,
				id: 79,
				selected: false,
			},
			{
				note: 3,
				startBeat: 11.5,
				endBeat: 11.75,
				velocity: 0.9,
				correct: true,
				id: 80,
				selected: false,
			},
		],
		[
			{
				note: 4,
				startBeat: 1,
				endBeat: 1.5,
				velocity: 0.9,
				correct: true,
				id: 24,
				selected: false,
			},
			{
				note: 4,
				startBeat: 9,
				endBeat: 9.25,
				velocity: 0.9,
				correct: true,
				id: 55,
				selected: false,
			},
		],
		[
			{
				note: 5,
				startBeat: 6.5,
				endBeat: 6.75,
				velocity: 0.9,
				correct: true,
				id: 51,
				selected: false,
			},
			{
				note: 5,
				startBeat: 7,
				endBeat: 7.25,
				velocity: 0.9,
				correct: true,
				id: 52,
				selected: false,
			},
			{
				note: 5,
				startBeat: 7.5,
				endBeat: 7.75,
				velocity: 0.9,
				correct: true,
				id: 53,
				selected: false,
			},
			{
				note: 5,
				startBeat: 14.5,
				endBeat: 14.75,
				velocity: 0.9,
				correct: true,
				id: 83,
				selected: false,
			},
		],
		[
			{
				note: 6,
				startBeat: 0,
				endBeat: 0.5,
				velocity: 0.9,
				correct: true,
				id: 23,
				selected: false,
			},
			{
				note: 6,
				startBeat: 1.5,
				endBeat: 1.625,
				velocity: 0.9,
				correct: true,
				id: 30,
				selected: false,
			},
			{
				note: 6,
				startBeat: 1.625,
				endBeat: 1.75,
				velocity: 0.9,
				correct: true,
				id: 33,
				selected: false,
			},
			{
				note: 6,
				startBeat: 1.75,
				endBeat: 1.875,
				velocity: 0.9,
				correct: true,
				id: 36,
				selected: false,
			},
			{
				note: 6,
				startBeat: 1.875,
				endBeat: 2,
				velocity: 0.9,
				correct: true,
				id: 38,
				selected: false,
			},
			{
				note: 6,
				startBeat: 3,
				endBeat: 3.25,
				velocity: 0.9,
				correct: true,
				id: 41,
				selected: false,
			},
			{
				note: 6,
				startBeat: 3.25,
				endBeat: 3.5,
				velocity: 0.9,
				correct: true,
				id: 44,
				selected: false,
			},
			{
				note: 6,
				startBeat: 5,
				endBeat: 5.25,
				velocity: 0.9,
				correct: true,
				id: 47,
				selected: false,
			},
			{
				note: 6,
				startBeat: 5.5,
				endBeat: 5.75,
				velocity: 0.9,
				correct: true,
				id: 48,
				selected: false,
			},
			{
				note: 6,
				startBeat: 8,
				endBeat: 8.25,
				velocity: 0.9,
				correct: true,
				id: 54,
				selected: false,
			},
			{
				note: 6,
				startBeat: 11,
				endBeat: 11.25,
				velocity: 0.9,
				correct: true,
				id: 60,
				selected: false,
			},
			{
				note: 6,
				startBeat: 11.25,
				endBeat: 11.5,
				velocity: 0.9,
				correct: true,
				id: 63,
				selected: false,
			},
			{
				note: 6,
				startBeat: 13,
				endBeat: 13.25,
				velocity: 0.9,
				correct: true,
				id: 67,
				selected: false,
			},
			{
				note: 6,
				startBeat: 13.5,
				endBeat: 13.75,
				velocity: 0.9,
				correct: true,
				id: 68,
				selected: false,
			},
			{
				note: 6,
				startBeat: 15,
				endBeat: 15.25,
				velocity: 0.9,
				correct: true,
				id: 70,
				selected: false,
			},
			{
				note: 6,
				startBeat: 15.5,
				endBeat: 15.75,
				velocity: 0.9,
				correct: true,
				id: 81,
				selected: false,
			},
		],
	];
};
